name: Upload Web Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  web:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    name: "Build & Upload: Web"
    steps:
    - uses: mymindstorm/setup-emsdk@v12
    - name: Verify
      run: emcc -v
    - uses: actions/checkout@v3
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Build with Make
      run: cd web && mkdir bin && make
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './web/bin'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
  
    - uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: html
        ITCH_GAME: gng
        ITCH_USER: crossscardev
        PACKAGE: web/gng-web.zip

  linux:
    runs-on: ubuntu-latest
    name: "Build & Upload: Linux"
    steps:
      - uses: actions/checkout@v3
      - name: Build with Make
        run: cd linux && mkdir bin && make

      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: gng
          ITCH_USER: crossscardev
          PACKAGE: linux/gng.deb
  
  wiiu:
    runs-on: ubuntu-latest
    name: "Build & Upload: Wii U"
    steps:
      - uses: actions/checkout@v3
      - name: Build with Make
        run: cd wiiu && mkdir -p bin/gng-wiiu && make

      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: gng
          ITCH_USER: crossscardev
          PACKAGE: wiiu/bin
